### ISSUE TITLE
Subsections

### ISSUE THREAD

**Issue by Sifor** [devinberg/ASEE-Conferences-Latex-Template#11]
Subsection headings are larger than section headings.

**Comment by Sifor** [comment]
Single space between headings and text.
Seems a little padded now. any way to fix?

**Comment by devinberg** [comment]
So I'm not really sure what to do with subsections. I typically don't use them personally. The [ASEE guideline](https://www.asee.org/documents/conferences/annual/2018/2018-Authors-Kit.pdf) provides no insight on their preference. You could try adding 
`\titleformat*{\subsection}{\normalsize\itshape} % Makes section titles 12 pt font italic`
at line 17 which would create a 12pt italic sub-heading. I don't think you'd want to make the text smaller because then it would be smaller than the body text.

For section spacing, you could try what I found [here](https://tex.stackexchange.com/questions/53338/reducing-spacing-after-headings).

Add the `titlesec` package with: `\usepackage{titlesec}`

Then add something like this around line 17 also:
`\titlespacing\section{0pt}{12pt plus 2pt minus 0pt}{0pt plus 2pt minus 2pt}`
`\titlespacing\subsection{0pt}{12pt plus 2pt minus 0pt}{0pt plus 2pt minus 2pt}`
